
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { map } from 'lucide-react';

interface TravelResultsProps {
  travelPlan: string;
}

const TravelResults: React.FC<TravelResultsProps> = ({ travelPlan }) => {
  const copyToClipboard = () => {
    navigator.clipboard.writeText(travelPlan);
  };

  const formatTravelPlan = (plan: string) => {
    // Split the plan into sections and format with proper spacing
    return plan.split('\n').map((line, index) => {
      if (line.trim() === '') return <br key={index} />;
      
      // Check if line is a heading (starts with ##, #, or numbers followed by .)
      if (line.match(/^#+\s/) || line.match(/^\d+\.\s/) || line.match(/^[A-Z\s]+:$/)) {
        return (
          <h3 key={index} className="font-bold text-lg text-blue-800 mt-4 mb-2">
            {line.replace(/^#+\s/, '')}
          </h3>
        );
      }
      
      // Check if line is a bullet point
      if (line.match(/^[\s\-\*•]/)) {
        return (
          <li key={index} className="ml-4 mb-1 text-gray-700">
            {line.replace(/^[\s\-\*•]+/, '')}
          </li>
        );
      }
      
      return (
        <p key={index} className="mb-2 text-gray-700 leading-relaxed">
          {line}
        </p>
      );
    });
  };

  return (
    <Card className="mt-8 shadow-2xl border-0 bg-gradient-to-br from-white to-blue-50">
      <CardHeader className="text-center border-b bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-t-lg">
        <div className="flex justify-center mb-2">
          <map className="w-8 h-8" />
        </div>
        <CardTitle className="text-2xl font-bold">
          Your Personalized Travel Plan
        </CardTitle>
        <p className="text-blue-100">Generated by AI • Tailored for you</p>
      </CardHeader>
      <CardContent className="p-8">
        <div className="prose prose-lg max-w-none">
          <div className="bg-white rounded-lg p-6 shadow-sm border border-gray-100">
            {formatTravelPlan(travelPlan)}
          </div>
        </div>
        
        <div className="flex justify-center mt-8">
          <Button 
            onClick={copyToClipboard}
            variant="outline"
            className="border-blue-300 text-blue-600 hover:bg-blue-50 hover:border-blue-400 px-6 py-2"
          >
            Copy Travel Plan
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default TravelResults;
